data_templetScene={
Scene={
[1]={
Layers1=1550,
image="newRes/building/orangeInstance.png",
Layers2=850,
image="newRes/building/orangeInstance.png",
Layers3=550,
image="newRes/building/orangeInstance.png",
positionY=20,
},
[2]={
Layers1=1550,
image="newRes/building/orangeInstance.png",
Layers2=850,
image="newRes/building/orangeInstance.png",
Layers3=550,
image="newRes/building/orangeInstance.png",
positionY=20,
},
},
Transmit={
[1]={
npc_name="老张",
docs="嘿，我是隔壁的老张呀",
type_id=4,
image="newRes/building/orangeInstance.png",
name_image="newRes/building/title_orangeInstance.png",
},
},
}-- end of file
